### PR TITLE
Correctly detect pid_file if set cwd option

### PR DESCRIPTION
**Pull request by Logioniz**
I think that this is small bug when calculating pid file.

### CODE REVIEW

**Comment by akarelas** [comment]
Thank you for your contribution. I have one question.

In this line:
```perl
my $pid_file = $opt->{pid_file} // catfile($opt->{cwd} // '', dirname($app), 'hypnotoad.pid');
```
...you seem to assume that dirname($app) returns a relative path. What if dirname($app) is an absolute path? Should it still be concatenated with `$opt->{cwd}` ?

**Comment by Logioniz** [comment]
Oh yes, i think that $app is a relative path when set cwd.
I see two ways what to do:
1) close pull request and nothing do
2) add check that $app begins with /

**Comment by Logioniz** [comment]
I decide that need to close pull request.

**Comment by akarelas** [comment]
Sorry to see it close.

**Comment by Logioniz** [comment]
I think that found a bug, but it is not true, so i close and delete fork.
If you want i may fork again and make new pull request or reopen current if it possible, because i have this code locally in my machine. Also add check that $app begins with /.

**Comment by akarelas** [comment]
File::Spec::Functions contains a function called ``file_name_is_absolute``. I wonder whether we should use this, for compatibility with Windows.

**Pull request closed without merging**
